config/routes.rb
Rails.application.routes.draw do
  resources :albums
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:artist_external_id, :album_name, :year)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(user_params)
    resource.save
    respond_with resource
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
  def user_params
    params.require(:user).permit(:username, :email, :full_name, :password, :passowrd_confirmation)
  end
  
  def respond_with(resource, _opts = {})
    if !resource.errors.empty?
      render json: {errors: resource.errors}, status: :bad_request
    else
      render json: resource
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def artists_select_options
    ArtistService.get_artists.map do |artist|
      [
        artist[0][:name],
        artist[0][:id]
      ]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Artist external:</strong>
    <%= album.artist_external_id %>
  </p>

  <p>
    <strong>Album name:</strong>
    <%= album.album_name %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= album.year %>
  </p>

</div>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :artist_external_id, class: 'form-label' %>
    <%= form.select :artist_external_id, artists_select_options, { prompt: "Select an artist" }, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :album_name, class: 'form-label' %>
    <%= form.text_field :album_name, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :year, class: 'form-label' %>
    <%= form.date_field :year, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Albums</h1>

<div id="albums">
  <% @albums.each do |album| %>
    <%= render album %>
    <p>
      <%= link_to "Show this album", album %>
    </p>
  <% end %>
</div>

<%= link_to "New album", new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>

<div>
  <%= link_to "Edit this album", edit_album_path(@album) %> |
  <%= link_to "Back to albums", albums_path %>

  <%= button_to "Destroy this album", @album, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moatbuilders</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice d-none"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>